import {
  Diet,
  MainOrigin,
  Meal,
  Price,
  Restaurant,
  Speed,
  SubOrigin,
  Tag,
} from "./types";

export const RESTAURANTS: Restaurant[] = [
  {
    name: "Nam Nam",
    origins: [MainOrigin.ASIA],
    meals: [Meal.BENTO],
    tags: [Tag.RESTAURANT],
    diets: [Diet.HEALTHY, Diet.VEGETARIAN],
    speed: Speed.FAST,
    price: Price.$$,
    hasTerrace: false,
    hasToilets: true,
    acceptsTakeAway: true,
    acceptsEatIn: true,
    acceptsCustomerBowl: false,
    mapsLink: "https://goo.gl/maps/dCrUQAfN65Ar5t6u8",
  },
  {
    name: "Mangez et cassez-vous !",
    origins: [SubOrigin.FRANCE],
    meals: [Meal.BURGER],
    tags: [Tag.RESTAURANT],
    diets: [Diet.JUNK, Diet.HALAL],
    speed: Speed.FAST,
    price: Price.$,
    hasTerrace: false,
    hasToilets: true,
    acceptsTakeAway: true,
    acceptsEatIn: true,
    acceptsCustomerBowl: false,
    mapsLink: "https://g.page/mangez-et-cassez-vous-lafayette?share",
  },
  {
    name: "Elgi - Lafayette",
    origins: [SubOrigin.FRANCE],
    meals: [Meal.SALAD],
    tags: [Tag.RESTAURANT],
    diets: [Diet.HEALTHY, Diet.VEGETARIAN],
    speed: Speed.FAST,
    price: Price.$$$,
    hasTerrace: false,
    hasToilets: false,
    acceptsTakeAway: true,
    acceptsEatIn: true,
    acceptsCustomerBowl: false,
    mapsLink: "https://goo.gl/maps/gY86f6Y8b5V87YNJ9",
  },
  {
    name: "Spok - Choiseul",
    origins: [SubOrigin.FRANCE],
    meals: [Meal.PLATE],
    tags: [Tag.RESTAURANT],
    diets: [Diet.HEALTHY],
    speed: Speed.FAST,
    price: Price.$$$,
    hasTerrace: false,
    hasToilets: false,
    acceptsTakeAway: true,
    acceptsEatIn: true,
    acceptsCustomerBowl: false,
    mapsLink: "https://goo.gl/maps/CthLS1wKUU5gA2KL6",
  },
  {
    name: "Canal Poké - Opéra",
    origins: [SubOrigin.HAWAII],
    meals: [Meal.POKEBOWL],
    tags: [Tag.RESTAURANT],
    diets: [Diet.HEALTHY, Diet.VEGETARIAN],
    speed: Speed.FAST,
    price: Price.$$$,
    hasTerrace: false,
    hasToilets: false,
    acceptsTakeAway: true,
    acceptsEatIn: true,
    acceptsCustomerBowl: false,
    mapsLink: "https://g.page/canalpokeopera?share",
  },
  {
    name: "Chipotle Mexican Grill",
    origins: [SubOrigin.MEXICO],
    meals: [Meal.BURRITO, Meal.PLATE],
    tags: [Tag.RESTAURANT],
    diets: [Diet.HEALTHY, Diet.JUNK],
    speed: Speed.FAST,
    price: Price.$$$,
    hasTerrace: false,
    hasToilets: true,
    acceptsTakeAway: true,
    acceptsEatIn: true,
    acceptsCustomerBowl: false,
    mapsLink: "https://goo.gl/maps/Z3ufmtMCfUhb6ecS9",
  },
  {
    name: "McDonald's - Bd. Haussmann",
    origins: [SubOrigin.USA],
    meals: [Meal.BURGER],
    tags: [Tag.RESTAURANT],
    diets: [Diet.JUNK, Diet.VEGETARIAN],
    speed: Speed.FAST,
    price: Price.$$,
    hasTerrace: false,
    hasToilets: true,
    acceptsTakeAway: true,
    acceptsEatIn: true,
    acceptsCustomerBowl: false,
    mapsLink: "https://goo.gl/maps/sR9WQunXzH5AJnAu7",
  },
  {
    name: "Cojean - Figaro",
    origins: [SubOrigin.FRANCE],
    meals: [Meal.SANDWICH, Meal.SALAD, Meal.PLATE],
    tags: [Tag.RESTAURANT],
    diets: [Diet.HEALTHY, Diet.VEGETARIAN],
    speed: Speed.FAST,
    price: Price.$$$$,
    hasTerrace: false,
    hasToilets: true,
    acceptsTakeAway: true,
    acceptsEatIn: true,
    acceptsCustomerBowl: false,
    mapsLink: "https://g.page/cojean-figaro?share",
  },
  {
    name: "Aki Café",
    origins: [SubOrigin.JAPAN],
    meals: [Meal.BENTO, Meal.PLATE, Meal.TEA],
    tags: [Tag.RESTAURANT],
    diets: [Diet.HEALTHY, Diet.VEGETARIAN],
    speed: Speed.FAST,
    price: Price.$$$,
    hasTerrace: false,
    hasToilets: false,
    acceptsTakeAway: true,
    acceptsEatIn: true,
    acceptsCustomerBowl: false,
    mapsLink: "https://goo.gl/maps/wHm84aB53AjCrC8k8",
  },
  {
    name: "Monop'",
    origins: [SubOrigin.FRANCE],
    meals: [Meal.ALCOHOL, Meal.SALAD],
    tags: [Tag.GROCERY],
    diets: [Diet.HEALTHY, Diet.VEGETARIAN],
    speed: Speed.FAST,
    price: Price.$$,
    hasTerrace: false,
    hasToilets: false,
    acceptsTakeAway: true,
    acceptsEatIn: true,
    acceptsCustomerBowl: false,
    mapsLink: "https://goo.gl/maps/yyeUCLHaTKdgqDBn7",
  },
  {
    name: "Veggie Tasty",
    origins: [SubOrigin.FRANCE],
    meals: [Meal.SALAD, Meal.BURRITO],
    tags: [Tag.RESTAURANT],
    diets: [Diet.HEALTHY, Diet.VEGETARIAN, Diet.VEGAN],
    speed: Speed.FAST,
    price: Price.$$$,
    hasTerrace: false,
    hasToilets: false,
    acceptsTakeAway: true,
    acceptsEatIn: true,
    acceptsCustomerBowl: false,
    mapsLink: "https://goo.gl/maps/YaXHN3rnvzCKh2uX6",
  },
  {
    name: "Burger King",
    origins: [SubOrigin.USA],
    meals: [Meal.BURGER],
    tags: [Tag.RESTAURANT],
    diets: [Diet.JUNK, Diet.VEGETARIAN],
    speed: Speed.FAST,
    price: Price.$$,
    hasTerrace: true,
    hasToilets: true,
    acceptsTakeAway: true,
    acceptsEatIn: true,
    acceptsCustomerBowl: false,
    mapsLink: "https://goo.gl/maps/ysKXMFK3E5msCePS9",
  },
  {
    name: "Bio Burger - Victoire",
    origins: [SubOrigin.FRANCE],
    meals: [Meal.BURGER],
    tags: [Tag.RESTAURANT],
    diets: [Diet.HEALTHY, Diet.JUNK, Diet.VEGETARIAN],
    speed: Speed.FAST,
    price: Price.$$$,
    hasTerrace: false,
    hasToilets: true,
    acceptsTakeAway: true,
    acceptsEatIn: true,
    acceptsCustomerBowl: false,
    mapsLink: "https://g.page/bioburger-victoire?share",
  },
  {
    name: "Hanoï Cà Phê - Opéra",
    origins: [SubOrigin.VIETNAM],
    meals: [Meal.ALCOHOL, Meal.SALAD, Meal.PLATE],
    tags: [Tag.RESTAURANT],
    diets: [Diet.HEALTHY, Diet.VEGETARIAN],
    speed: Speed.MEDIUM,
    price: Price.$$$$,
    hasTerrace: true,
    hasToilets: true,
    acceptsTakeAway: true,
    acceptsEatIn: true,
    acceptsCustomerBowl: false,
    mapsLink: "https://goo.gl/maps/XZ1MyHTPkT6WRDHy5",
  },
  {
    name: "Côme - Lafayette",
    origins: [SubOrigin.FRANCE],
    meals: [Meal.SALAD, Meal.BURRITO, Meal.JUICE],
    tags: [Tag.RESTAURANT],
    diets: [Diet.HEALTHY],
    speed: Speed.FAST,
    price: Price.$$$,
    hasTerrace: true,
    hasToilets: true,
    acceptsTakeAway: true,
    acceptsEatIn: true,
    acceptsCustomerBowl: false,
    mapsLink: "https://goo.gl/maps/mVK7XeNihychuTxp6",
  },
  {
    name: "Higuma",
    origins: [SubOrigin.JAPAN],
    meals: [Meal.BENTO, Meal.RAMEN, Meal.ALCOHOL],
    tags: [Tag.RESTAURANT],
    diets: [Diet.HEALTHY],
    speed: Speed.FAST,
    price: Price.$$,
    hasTerrace: true,
    hasToilets: true,
    acceptsTakeAway: true,
    acceptsEatIn: true,
    acceptsCustomerBowl: false,
    mapsLink: "https://goo.gl/maps/A6Qrbg2ahEVnSFAN7",
  },
  {
    name: "Le 37m²",
    origins: [SubOrigin.TAIWAN],
    meals: [Meal.BENTO, Meal.TEA, Meal.BUBBLE_TEA],
    tags: [Tag.RESTAURANT],
    diets: [Diet.HEALTHY, Diet.VEGETARIAN],
    speed: Speed.FAST,
    price: Price.$$,
    hasTerrace: false,
    hasToilets: true,
    acceptsTakeAway: true,
    acceptsEatIn: true,
    acceptsCustomerBowl: false,
    mapsLink: "https://goo.gl/maps/3jnbNp6cg8uPmJeT7",
  },
  {
    name: "Le Papacionu Paris",
    origins: [SubOrigin.ITALIA],
    meals: [Meal.PIZZA, Meal.ALCOHOL],
    tags: [Tag.RESTAURANT],
    diets: [Diet.JUNK, Diet.VEGETARIAN],
    speed: Speed.MEDIUM,
    price: Price.$$$,
    hasTerrace: true,
    hasToilets: true,
    acceptsTakeAway: true,
    acceptsEatIn: true,
    acceptsCustomerBowl: false,
    mapsLink: "https://g.page/papacionuparis?share",
  },
  {
    name: "Little Baobei",
    origins: [MainOrigin.ASIA],
    meals: [Meal.BURGER],
    tags: [Tag.RESTAURANT],
    diets: [Diet.JUNK],
    speed: Speed.MEDIUM,
    price: Price.$$$$,
    hasTerrace: true,
    hasToilets: false,
    acceptsTakeAway: true,
    acceptsEatIn: true,
    acceptsCustomerBowl: false,
    mapsLink: "https://g.page/littlebaobeiparis?share",
  },
  {
    name: "Pizzeria Popolare",
    origins: [SubOrigin.ITALIA],
    meals: [Meal.PIZZA, Meal.PASTA, Meal.ALCOHOL],
    tags: [Tag.RESTAURANT],
    diets: [Diet.JUNK, Diet.VEGETARIAN],
    speed: Speed.MEDIUM,
    price: Price.$$$$,
    hasTerrace: false,
    hasToilets: true,
    acceptsTakeAway: true,
    acceptsEatIn: true,
    acceptsCustomerBowl: false,
    mapsLink: "https://goo.gl/maps/V5WYnQy9cPBJ96NbA",
  },
  {
    name: "Di Loretta",
    origins: [SubOrigin.ITALIA],
    meals: [Meal.PIZZA],
    tags: [Tag.RESTAURANT],
    diets: [Diet.JUNK, Diet.VEGETARIAN],
    speed: Speed.FAST,
    price: Price.$$$,
    hasTerrace: false,
    hasToilets: false,
    acceptsTakeAway: true,
    acceptsEatIn: true,
    acceptsCustomerBowl: false,
    mapsLink: "https://goo.gl/maps/rBNxTks5z1oWAyGF8",
  },
  {
    name: "So Nat - Notre Dame de Lorette",
    origins: [SubOrigin.FRANCE],
    meals: [Meal.SALAD, Meal.JUICE],
    tags: [Tag.RESTAURANT],
    diets: [Diet.HEALTHY, Diet.VEGETARIAN, Diet.VEGAN],
    speed: Speed.FAST,
    price: Price.$$$,
    hasTerrace: false,
    hasToilets: false,
    acceptsTakeAway: true,
    acceptsEatIn: true,
    acceptsCustomerBowl: false,
    mapsLink: "https://goo.gl/maps/jyEmrcuCY5fFFEn86",
  },
  {
    name: "Mongoo - Madeleine",
    origins: [SubOrigin.FRANCE],
    meals: [Meal.SALAD, Meal.ALCOHOL],
    tags: [Tag.RESTAURANT],
    diets: [Diet.HEALTHY, Diet.VEGETARIAN, Diet.VEGAN],
    speed: Speed.FAST,
    price: Price.$$,
    hasTerrace: false,
    hasToilets: true,
    acceptsTakeAway: true,
    acceptsEatIn: true,
    acceptsCustomerBowl: false,
    mapsLink: "https://goo.gl/maps/errTRfDjPvcvtrDNA",
  },
  {
    name: "Super Cocotte",
    origins: [SubOrigin.FRANCE],
    meals: [Meal.PLATE],
    tags: [Tag.RESTAURANT],
    diets: [Diet.HEALTHY],
    speed: Speed.MEDIUM,
    price: Price.$$$,
    hasTerrace: false,
    hasToilets: false,
    acceptsTakeAway: true,
    acceptsEatIn: true,
    acceptsCustomerBowl: false,
    mapsLink: "https://goo.gl/maps/A3XpMPc9tHHDraJZ8",
  },
  {
    name: "Ristorante Del Arte - Hausmann",
    origins: [SubOrigin.ITALIA],
    meals: [Meal.PIZZA, Meal.PASTA, Meal.PLATE],
    tags: [Tag.RESTAURANT],
    diets: [Diet.HEALTHY, Diet.JUNK, Diet.VEGETARIAN],
    speed: Speed.FAST,
    price: Price.$$$$,
    hasTerrace: false,
    hasToilets: true,
    acceptsTakeAway: true,
    acceptsEatIn: true,
    acceptsCustomerBowl: false,
    mapsLink: "https://goo.gl/maps/MNiZRYY4swomWPzW9",
  },
  {
    name: "Clémentine",
    origins: [SubOrigin.FRANCE],
    meals: [Meal.PLATE, Meal.ALCOHOL],
    tags: [Tag.RESTAURANT],
    diets: [Diet.HEALTHY],
    speed: Speed.MEDIUM,
    price: Price.$$$$,
    hasTerrace: false,
    hasToilets: false,
    acceptsTakeAway: true,
    acceptsEatIn: true,
    acceptsCustomerBowl: false,
    mapsLink: "https://g.page/TerrasseClementineParis?share",
  },
  {
    name: "Goiko",
    origins: [SubOrigin.COLOMBIA],
    meals: [Meal.BURGER, Meal.SALAD, Meal.ALCOHOL],
    tags: [Tag.RESTAURANT, Tag.BRASSERIE],
    diets: [Diet.JUNK, Diet.VEGETARIAN],
    speed: Speed.MEDIUM,
    price: Price.$$$$,
    hasTerrace: false,
    hasToilets: true,
    acceptsTakeAway: true,
    acceptsEatIn: true,
    acceptsCustomerBowl: false,
    mapsLink: "https://goo.gl/maps/WSJYZXrYgWBusQvG7",
  },
  {
    name: "Chez Papa",
    origins: [SubOrigin.FRANCE],
    meals: [Meal.PLATE, Meal.BURGER, Meal.ALCOHOL],
    tags: [Tag.RESTAURANT],
    diets: [Diet.HEALTHY],
    speed: Speed.MEDIUM,
    price: Price.$$$$,
    hasTerrace: true,
    hasToilets: true,
    acceptsTakeAway: true,
    acceptsEatIn: true,
    acceptsCustomerBowl: false,
    mapsLink: "https://goo.gl/maps/ktR5db6Qe1Y7kih26",
  },
  {
    name: "Au Petit Riche",
    origins: [SubOrigin.FRANCE],
    meals: [Meal.PLATE, Meal.ALCOHOL],
    tags: [Tag.RESTAURANT, Tag.BRASSERIE],
    diets: [Diet.HEALTHY],
    speed: Speed.SLOW,
    price: Price.$$$$$,
    hasTerrace: false,
    hasToilets: true,
    acceptsTakeAway: false,
    acceptsEatIn: true,
    acceptsCustomerBowl: false,
    mapsLink: "https://g.page/aupetitriche?share",
  },
  {
    name: "Le Sâotico",
    origins: [SubOrigin.FRANCE],
    meals: [Meal.PLATE, Meal.ALCOHOL],
    tags: [Tag.RESTAURANT],
    diets: [Diet.HEALTHY],
    speed: Speed.MEDIUM,
    price: Price.$$$$,
    hasTerrace: false,
    hasToilets: true,
    acceptsTakeAway: true,
    acceptsEatIn: true,
    acceptsCustomerBowl: false,
    mapsLink: "https://g.page/restaurant-le-saotico?share",
  },
  {
    name: "Gyoza House",
    origins: [SubOrigin.JAPAN],
    meals: [Meal.BENTO, Meal.ALCOHOL],
    tags: [Tag.RESTAURANT],
    diets: [Diet.HEALTHY, Diet.JUNK, Diet.VEGETARIAN, Diet.HALAL],
    speed: Speed.FAST,
    price: Price.$$$,
    hasTerrace: false,
    hasToilets: true,
    acceptsTakeAway: true,
    acceptsEatIn: true,
    acceptsCustomerBowl: false,
    mapsLink: "https://g.page/gyoza-house?share",
  },
  {
    name: "Vaudeville",
    origins: [SubOrigin.FRANCE],
    meals: [Meal.PLATE, Meal.SEAFOOD, Meal.ALCOHOL],
    tags: [Tag.RESTAURANT],
    diets: [Diet.HEALTHY],
    speed: Speed.SLOW,
    price: Price.$$$$,
    hasTerrace: true,
    hasToilets: true,
    acceptsTakeAway: false,
    acceptsEatIn: true,
    acceptsCustomerBowl: false,
    mapsLink: "https://goo.gl/maps/SBFPeNZKkNQM2cCp7",
  },
  {
    name: "Le Chenin",
    origins: [SubOrigin.FRANCE],
    meals: [Meal.PLATE, Meal.ALCOHOL],
    tags: [Tag.RESTAURANT, Tag.BRASSERIE],
    diets: [Diet.HEALTHY],
    speed: Speed.MEDIUM,
    price: Price.$$$$,
    hasTerrace: false,
    hasToilets: false,
    acceptsTakeAway: true,
    acceptsEatIn: true,
    acceptsCustomerBowl: false,
    mapsLink: "https://goo.gl/maps/wQYpcBvNLsxedXKTA",
  },
  {
    name: "Kintaro",
    origins: [SubOrigin.JAPAN],
    meals: [Meal.BENTO, Meal.PLATE, Meal.RAMEN, Meal.ALCOHOL],
    tags: [Tag.RESTAURANT],
    diets: [Diet.HEALTHY, Diet.VEGETARIAN],
    speed: Speed.MEDIUM,
    price: Price.$$$,
    hasTerrace: true,
    hasToilets: true,
    acceptsTakeAway: true,
    acceptsEatIn: true,
    acceptsCustomerBowl: false,
    mapsLink: "https://goo.gl/maps/GnywunSB2fLxAicL7",
  },
  {
    name: "Kouki",
    origins: [SubOrigin.JAPAN, SubOrigin.MEXICO],
    meals: [Meal.SALAD, Meal.POKEBOWL, Meal.ALCOHOL],
    tags: [Tag.RESTAURANT],
    diets: [Diet.HEALTHY, Diet.JUNK, Diet.VEGETARIAN],
    speed: Speed.FAST,
    price: Price.$$$,
    hasTerrace: true,
    hasToilets: true,
    acceptsTakeAway: true,
    acceptsEatIn: true,
    acceptsCustomerBowl: false,
    mapsLink: "https://g.page/eatkouki?share",
  },
  {
    name: "Hard Rock Café",
    origins: [SubOrigin.USA],
    meals: [Meal.BURGER, Meal.PLATE, Meal.SALAD, Meal.SANDWICH, Meal.ALCOHOL],
    tags: [Tag.RESTAURANT, Tag.BRASSERIE],
    diets: [Diet.HEALTHY, Diet.JUNK, Diet.VEGETARIAN],
    speed: Speed.FAST,
    price: Price.$$$,
    hasTerrace: true,
    hasToilets: true,
    acceptsTakeAway: true,
    acceptsEatIn: true,
    acceptsCustomerBowl: false,
    mapsLink: "https://g.page/hardrockcafeparis?share",
  },
  {
    name: "Bambou",
    origins: [SubOrigin.THAILAND],
    meals: [Meal.PLATE, Meal.SALAD, Meal.ALCOHOL],
    tags: [Tag.RESTAURANT, Tag.BRASSERIE],
    diets: [Diet.HEALTHY, Diet.VEGETARIAN],
    speed: Speed.SLOW,
    price: Price.$$$$$,
    hasTerrace: true,
    hasToilets: true,
    acceptsTakeAway: true,
    acceptsEatIn: true,
    acceptsCustomerBowl: false,
    mapsLink: "https://g.page/bambouparis?share",
  },
  {
    name: "Hippopotamus",
    origins: [SubOrigin.FRANCE],
    meals: [
      Meal.PLATE,
      Meal.BURGER,
      Meal.ALCOHOL,
      Meal.ICE_CREAM,
      Meal.SEAFOOD,
    ],
    tags: [Tag.RESTAURANT, Tag.BRASSERIE],
    diets: [Diet.HEALTHY, Diet.VEGETARIAN],
    speed: Speed.MEDIUM,
    price: Price.$$$$,
    hasTerrace: true,
    hasToilets: true,
    acceptsTakeAway: true,
    acceptsEatIn: true,
    acceptsCustomerBowl: false,
    mapsLink: "https://goo.gl/maps/kTtUZ7ZZ5APyMvnU9",
  },
  {
    name: "Restaurant Thaï Thaï",
    origins: [SubOrigin.THAILAND],
    meals: [Meal.PLATE, Meal.ALCOHOL, Meal.TEA, Meal.SMOOTHIE, Meal.SOUP],
    tags: [Tag.RESTAURANT, Tag.BRASSERIE],
    diets: [Diet.HEALTHY, Diet.VEGETARIAN],
    speed: Speed.MEDIUM,
    price: Price.$$$$,
    hasTerrace: true,
    hasToilets: true,
    acceptsTakeAway: true,
    acceptsEatIn: true,
    acceptsCustomerBowl: false,
    mapsLink: "https://goo.gl/maps/ENBzQbtowbbcz5ns9",
  },
];
